import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section id='home' className='bg-cyan-900 flex h-screen'>
          <h1 className='m-auto text-slate-300 text-2xl'>Hero</h1>
        </section>
        <section id='projects' className='bg-rose-900 flex h-screen'>
          <h1 className='m-auto text-slate-300 text-2xl'>Projects</h1>
        </section>
        <section id='about' className='bg-cyan-900 flex h-screen'>
          <h1 className='m-auto text-slate-300 text-2xl'>About</h1>
        </section>
        <section id='contact' className='bg-rose-900 flex h-screen'>
          <h1 className='m-auto text-slate-300 text-2xl'>Contact</h1>
        </section>
      </main>
    </>
  )
}
