import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Homepage from './homepage'
import Projects from './projects'
import About from './about'
import Contact from './contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section id='homepage'>
          <Homepage />
        </section>
        <section id="projects">
          <Projects />
        </section>
        <section id='about'>
          <About />
        </section>
        <section id='contact'>
          <Contact />
        </section>
      </main>
    </>
  )
}
